SANDAG/ABM

- src/asim_cross_border/configs/settings.yaml
This change multi-processes the TVPB step (max number of processors appears to be 5). Also, starts mp_households at 'tour_scheduling_probabilistic' -- 0e329e856a64bdcbae536cbb2c9a65bb687bbee2 moved 'tour_od_choice' after this step in the model order but did not update the multi-processing order.
> Multiprocess TVPB step

- src/main/emme/toolbox/assignment/create_transit_connector.py
- src/main/emme/toolbox/master_run.py
- src/main/emme/toolbox/utilities/run_summary.py
- src/main/python/emme/run_transit_assignment.py
Fixes [AB#431](https://dev.azure.com/SANDAG-ADS/3af839ac-e181-4605-b11c-60f38a706246/_workitems/edit/431)
Minor additional runtime savings by adding additional transit assignment steps to parallelization. Saves about 1 hour in iteration 1 for transit connector creation, and about 0.5 hours per iteration in OMX skim export. Overall time savings for a full run should be around 3 hours.
> Add connector creation and OMX export to transit parallelization

- src/asim/configs/resident/settings.yaml
- src/asim/configs/resident/settings_mp.yaml
- src/asim/extensions/__init__.py
- src/asim/extensions/adjust_auto_operating_cost.py
Extra step to adjust the auto operating costs in the vehicles table to average out to costPerMile in constants.yaml (derived from aoc.fuel and aoc.maintenance in sandag_abm.properties)
> Add auto operating cost adjustment after vehicle type choice

- src/asim/configs/resident/vehicle_type_choice.yaml
- src/asim/configs/resident/vehicle_type_choice_annotate_alts_preprocessor.csv
- src/asim/configs/resident/vehicle_type_choice_op4.csv
Editing configs so recoding the fuel and body types as integers to save memory. Requires [this pull request](https://github.com/SANDAG/activitysim/pull/66) to be merged into the BayDAG_estimation branch of the ActivitySim source code.
> Recode body and fuel type as integers in vehicle type choice model

- src/main/python/pythonGUI/createStudyAndScenario.py
- src/main/resources/create_scenario.cmd
- The user can now select a land use scenario, which will copy the inputs for the desired year and scenario from the filepath defined [here](https://github.com/SANDAG/ABM/blob/ABM3_gui_lu/src/main/python/pythonGUI/createStudyAndScenario.py#L58). A land use scenario is only available for a given year if the year is listed under `"years"` for the scenario in `self.lu_options` (I based this on what was present at the time).
- The displayed release version is updated from 14.3.0 to 15.0.0.
- The default directory from the scenario was updated to prevent everything being copied into T:\projects\sr15 by mistake.
> Update ABM3 GUI to select land use scenario

- src/asim/configs/resident/tour_mode_choice_coefficients.csv
- src/asim/configs/resident/trip_mode_choice_coefficients.csv
`coef_calib_onboard` was mistakenly defined in the coefficient file for trip mode choice and not tour mode choice. This fixes that.
> Fix onboard tour mode choice coefficient

- src/asim/configs/airport.CBX/trip_mode_choice.yaml
- src/asim/configs/airport.SAN/trip_mode_choice.yaml
- src/asim/configs/common/constants.yaml
- src/asim/configs/crossborder/constants.yaml
Increase the value of the rail (commuter & light rail) in-vehicle-time multipliers from 0.65 to 0.85 to account for a rail bug related to transit transfer connectors being in feet rather than miles, which in turn over-estimated transit ridership when the connectors were fixed/converted to miles.
> Rail IVT Multipliers Update

- src/main/python/recodeSynthEstabToMGRA.py
When the establishment synthesis was changed to be at the TAZ level, the recoding of the zone IDs to an MGRA initially took the first MGRA for a given TAZ listed in the MGRA file. This changes it to randomly select an MGRA within the TAZ based on the total employment, resulting in an employment distribution that better matches the MGRA file.
> Improved Recoding of Synthetic Establishment MGRAs

- src/asim/configs/resident/tour_mode_choice_coefficients.csv
The value of coef_calib_onboard in resident tour mode choice was decreased.
A 10% sample of of the resident model resulted in 7522 transit tours. After multiplying by 10 this is only 0.9% below the target of 75,912.
> Decreased coef_calib_onboard in resident tour mode choice

- src/main/resources/runSandagAbm_ActivitySimXborderWaitModel.cmd
- src/main/resources/runSandagAbm_Preprocessing.cmd
Add the common config directory to the arguments for cross_border_model.py in runSandagAbm_Preprocessing.cmd and runSandagAbm_ActivitySimXborderWaitModel.cmd, needed because xborder model now uses common/constants.yaml
Fixes error when calling asim preprocessing or xborder wait
> Add common config arg to xborder asim call

- src/asim/scripts/xborder/cross_border_model.py
Add common config directory to arguments when calling simulation.py to run crossborder wait time model.
Fixes error when calling xborder wait
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...
> Add common config arg to xborder wait call

- build.cmd
When running build.cmd to rebuild an existing release, delete the existing version_x_x_x\common directory to remove any old files that may have been deleted in recent commits.
Prevents issues caused by files deleted on repo persisting in release
> Delete old files when rebuilding release

- src/main/python/pythonGUI/createStudyAndScenario.py
- src/main/resources/sandag_abm.properties
Replace land use dropdown in scenario creation GUI with a text field to enter the location of the land use directory.
Network directory and land use directory fields are updated to default to their respective root directories (T:\projects\sr15\land_use\2025RP_draft, T:\projects\sr15\tned_etl\2025RP_draft). The "..." button will browse this directory, allowing the user to select the desired subdirectory. Will give an error if attempting to create a scenario with invalid network or land use directory (trlink.csv or persons.csv are missing from the given folder).
Allows various land use scenarios to be selected, such as scenarios with different parking policies.
Please describe the tests that you ran …
> Select land use directory in GUI

- src/asim/configs/resident/telecommute_frequency_coeffs.csv
- src/asim/configs/resident/work_from_home_coeffs.csv
Lower WFH and telecommuting to improve highway validation and because HTS 2022 targets were a bit higher.
WFH share is expected to decrease from 9.36% to 8.95%. Regional VMT is expected to increase to about 77 million.
A partial run (3rd and 4th iterations) was conducted by adjusting coefficients by double of what is being committed in this PR.
No further comments.
> 195 calibrate wfh and telecommute frequency lower

- src/main/emme/toolbox/master_run.py
- src/main/emme/toolbox/model/external_internal.py
- src/main/emme/toolbox/utilities/file_manager.py
- src/main/resources/create_scenario.cmd
Removes code that creates and copies files to input_truck and visualizer folders, as these are unused and empty. Also removed references to some previously removed input folders.
Code and directory cleanliness
> Remove unused input_truck and visualizer folders in scenario

- src/asim/configs/resident/settings_mp.yaml
- src/asim/extensions/__init__.py
- src/asim/extensions/check_disk_usage.py
- src/main/emme/toolbox/master_run.py
- src/main/resources/sandag_abm.properties
Get scenario folder disk usage at end of resident model and end of scenario run before copying to T drive. Pipeline files are cleared at end of resident model, so max usage is expected to be at the end of iteration 3 resident before clearing pipeline. Disk usage check is commented out by default.
Current max disk usage for 2035 build is 422gb. Updated disk space check to 430gb to leave some breathing room.
Prevents starting runs without sufficient C drive space
> Get maximum disk usage, update disk space check

- src/asim/configs/resident/trip_mode_choice_coefficients.csv
The value of `coef_calib_flexfleet` in trip mode choice is increased by 0 to 8.5 so that the observed boardings will better match the base year values.
The NEV base year boarding targets are 433 for Downtown and 200 for Oceanside. With the coefficient being 0 the boardings were 138 and 27 for Downtown and Oceanside, respectively. Increasing the coefficient to 8.5 should bring them closer to the targets.
> Flexible fleet calibration to better match observed base year NEV boardings

- src/asim/configs/resident/vehicle_type_choice.yaml
- src/asim/configs/resident/vehicle_type_choice_op4.csv
- src/asim/configs/resident/vehicle_type_choice_op4_coefficients.csv
During the tests of the 2025 Regional Plan initial concept, it was found that increasing the number of EV chargers from 30,000 to 40,000 increased the share of vehicles that are EVs from 25% (what the no build scenario was calibrated to) to 97%. This pull request has the following changes:
- Reduces the EV ownership sensitivity to the number of chargers
- Edit the utility expression to have the sensitivity decrease exponentially over time (see below for explanation)
- Recalibrate the 2022, 2035, and 2050 shares to match the targets set by planning staff
A rerun of the recent 2035 no build and build runs found that the increase in EVs was from 25% to 33%, which is much more realistic and consistent with the literature we found (see below for explanation). It should be noted that the build …
> Reduce EV Charger Sensitivity

- src/main/python/TravelTimeReporter.py
The travel time reporter previously did not factor in the access or rent times for micromobility and didn't cap the distances at the maximum value. This pull request fixes that.
The travel times by ebike and escooter should increase and more OD-pairs will have values of 999.
> Add micromobility access to travel time reporter

- src/main/python/AMTravelTimeReporterConfigs.yaml
- src/main/python/MDTravelTimeReporterConfigs.yaml
- src/main/python/TravelTimeReporter.py
This pull request edits the travel time reporter script to factor in all transit modes, not just those with mixed paths. It looks up the local, premium, and mixed skims and takes the minimum.
More OD-pairs (that are only available via local or premium routes) should be factored into the transit time reporting.
> Include all transit modes in travel time reporter

- src/main/emme/toolbox/export/export_data_loader_network.py
- src/main/python/hwyShapeExport.py
This change trims down the width of the report/hwyTcad.csv file by dropping 121 columns (goes from 307 to 186 columns) that were identified to be irrelevant for reporting purposes, redundant, or simply not useful to report. 
The report/hwyTcad.csv file gets uploaded to our datalake system and will make the file easier to work with along with reducing clutter by making the table slimmer. 
For a complete list of attributes that were dropped, please refer to the following file: [hwy_tcad_columns.xlsx](https://sandag.sharepoint.com/:x:/r/sites/SANDAGModels/_layouts/15/Doc.aspx?sourcedoc=%7B04060CE2-5161-4790-BF16-E000DDF5BA15%7D&file=hwy_tca …
> Drop fields from hwytcad

- docs/application/flexible-fleets.md
- src/asim/configs/common/constants.yaml
The value of `maxWalkIfMTAccessAvailable` in configs\common\constants.yaml to be raised from a half mile to a mile. This would mean that if a flexible fleet service is available to take someone from a transit stop to their tour destination, they will assumed to walk if the destination is less than a mile from the transit station as opposed to a half mile.
A sensitivity test found that there was little change in direct flexible fleet trips. However, access and egress to fixed route transit (on the attraction end) decreased significantly.
> Increase maxWalkIfMTAccessAvailable from a half mile to a mile

- src/main/python/TravelTimeReporter.py
Travel time reporter was comparing skimmed drive time to maximum distance for flexible fleet, corrected this to use skimmed distance. Already correct in model.
Fix flexible fleet access numbers in performance metrics
> Fix max distance calculation in TravelTimeReporter.py

- src/main/emme/toolbox/master_run.py
- src/main/python/datalake_exporter.py
- src/main/python/pythonGUI/createStudyAndScenario.py
- src/main/resources/sandag_abm.properties
Automatically update the release version and path in the GUI, sandag_abm.properties, and scenario table.
Removes need to manually update version number in these places
> Automatically update release version in GUI and properties

- src/main/python/TravelTimeReporter.py
This removes the initial wait time for flexible fleets from the travel time reporter.
More destinations will be available within a trip of a specified time by microtransit or NEV.
No tests were run
> Removed flexible fleet wait time from travel time reporter

- src/main/emme/toolbox/assignment/build_transit_scenario.py
- src/main/emme/toolbox/assignment/transit_assignment.py
- src/main/emme/toolbox/export/export_data_loader_network.py
This pull request makes 2 (two) changes related to link transit travel times:
1. It assigns link transit travel times based on whether the link is a rail link or a bus-only street
2. For links that are split due to timed transfer virtual segments, this change sums up the link transit travel time between the 2 (two) newly created splits
The changes in this pull request:
1. Will redistribute ridership between different transit modes. In particular, rail-based routes will experience an increase in ridership, while street-based routes will experience a decrease due to bus-only streets having been unaccounted for travel times which resulted in lower travel times and hence higher utility and ridership.
2. Will eliminate negative and 0 (zero) reported values for BASEIVTT under …
> Link Transit Travel Times

- src/main/python/TravelTimeReporter.py
Removes line in travel time reporter that renames "OMAZ" and "DMAZ" columns in walk skims to "i" and "j". maz_maz_walk.csv now already contains "i" and "j" columns
Fixes error in travel time reporter caused by duplicate columns after renaming
> Remove rename in travel time reporter

- src/main/python/pythonGUI/createStudyAndScenario.py
Java processes would crash if release, network, or land use folders were in the "user" folder, as it would interpret "\user" in the file path as a unicode escape sequence. This update automatically replaces "\u" with "/u" in these file paths in sandag_abm.properties to prevent this.
Allows these folders to be in the user folder or other folders starting with "u"
> Fix java unicode error

- src/main/python/TravelTimeReporter.py
Travel time uses one function to read in both walk and bike skims. Walk skims now already contain "i", "j" columns, while bike skims do not. To fix this, check if skims contain "i" column and only rename if the column does not already exist.
Fix crash in TravelTimeReporter
> Fix active skim columns in travel time reporter

- src/asim/scripts/resident/resident_preprocessing.py
- src/main/python/TravelTimeReporter.py
When external zones are added to maz_maz_walk.csv, they were only added to OMAZ and DMAZ columns, not i and j columns. Updated to add external zones to these columns to avoid duplicate i and j values. Also updated travel time reporter to not use these i and j columns (not strictly necessary but better for consistency)
Fixes error in travel time reporter
> Fix external zones not added to i,j columns in walk skims

- src/main/python/AMTravelTimeReporterConfigs.yaml
- src/main/python/MDTravelTimeReporterConfigs.yaml
- src/main/python/TravelTimeReporter.py
- src/main/python/datalake_exporter.py
The MAZ-level bike and walk skims don't include all OD-pairs that can be accessed by those modes. This adds TAZ-level skims for OD-pairs that the MAZ-level skims show as unavailable.
More MGRA pairs should be available by bike and walking, increasing the number of opportunities in performance measures using those skims (such as jobs accessible by walking). Test results can be seen at T:\ABM\user\jflo\projects\ABM3\TravelTimeReporter\TestOutput30October.
> Include TAZ skims for travel times by active modes in Travel Time Reporter

- src/main/emme/toolbox/master_run.py
- src/main/emme/toolbox/utilities/properties.py
- src/main/python/pythonGUI/parameterEditor.py
- src/main/resources/sandag_abm.properties
Combines functionality of "Skip bike logsums" and "Skip copy of bike logsum" options. If "Skip bike logsums" is checked and bike logsums are not found in output, they will be copied from input
Removes unintuitive behavior where new logsums would be overwritten by old logsums when both options were checked.
> Remove "Skip copy of bike logsum"

- src/main/python/AMTravelTimeReporterConfigs.yaml
- src/main/python/MDTravelTimeReporterConfigs.yaml
- src/main/python/datalake_exporter.py
This increases the threshold used in the travel time reporter from 30 minutes to 45 minutes.
More and higher travel times between OD-pairs will be reported. There will also be a runtime increase in the travel time reporter.
No tests have been run.
> Increase travel time reporter threshold to 45 minutes

- src/main/emme/toolbox/master_run.py
- src/main/emme/toolbox/utilities/properties.py
Add checkbox in master run to skip travel time reporter. Previously was included in "skip data export"
Travel time reporter takes a long time to run, so this lets us skip it for scenarios where we do not need to run access PM.
> Add option to skip travel time reporter

- src/asim/configs/resident/workplace_location_coefficients.csv
[AB#1434](https://dev.azure.com/SANDAG-ADS/3af839ac-e181-4605-b11c-60f38a706246/_workitems/edit/1434)
Increased average work distance from 11.2 to 11.5. This was done to help increase 2022 VMT back to target, in combination with https://github.com/SANDAG/ABM/pull/259, after it was greatly reduced by https://github.com/SANDAG/ABM/pull/251
VMT increased by around 300k
Increasing external workplace location coef_dist_capped had no effect.
Increasing internal workplace location coef_dist from 0.27909 to 0.29 increased average work distance from 11.2 to 11.8, increasing VMT by 700k. This was about double the increase we wanted. so we tried …
> Increased average work distance

- src/main/python/pythonGUI/createStudyAndScenario.py
Adds 2032 and 2040 to the list of scenario years.
When creating a scenario 2032 and 2040 are now listed as options.
> Added 2032 and 2040 to scenario year options in scenario creation GUI

- src/main/python/TravelTimeReporter.py
Planners have asked that ebike is assumed to be owned and not shared when calculating access metrics. This removes the micro access time and micro rent time from the ebike time calculation.
More MGRAs should be accessible by ebike.
This change has not been tested
> Assume owned ebike in travel time reporter

- src/asim/configs/resident/tour_mode_choice_coefficients.csv
AT network was updated to set default vehicle lanes to 1 instead of 0 for links with no lane info. The result was far more suburban and rural streets allowing bikes, greatly increasing bike mode share. This recalibration reduces overall bike tour mode share with the new network.
Bike tour mode share:
- Pre-calibration: 2.05%
- Target: 1.47% (pre-update share)
- Calibration result: 1.46%
> Recalibrate bike mode share for updated network

- src/main/resources/runSandagAbm_MAAS.cmd
Propagate errors from TNC routing or AV allocation models to master_run so that the model crashes if they fail.
Same implementation as asim preprocessing https://github.com/SANDAG/ABM/blob/ABM3_develop/src/main/resources/runSandagAbm_Preprocessing.cmd
Model will crash instead of failing silently if MAAS models encounter an error
> Crash model if MAAS models fail

- src/asim/configs/resident/write_trip_matrices_annotate_trips_preprocessor.csv
- src/asim/visualizer/visualizer/config/user_added_functions.py
TNC Routing / AV Allocation errors out when first row of the trips table has a numerical value for escort_participants, as the column also contains string values. To fix this, add an underscore to the start of all escort_participants values to force it to be read as string. Visualizer is updated to account for this extra underscore
Prevent rare error in MAAS
> Force AV allocation to read escort_participants as string

- src/asim/configs/resident/write_trip_matrices_annotate_trips_preprocessor.csv
Visualizer crashed with recent changes to escort_participants due to "_" values: https://github.com/SANDAG/ABM/pull/274
Added parentheses appear to have fixed the issue
No crash in visualizer
> Fix escort participants in visualizer

- src/asim/visualizer/visualizer/config/settings.yaml
Edits the calibration visualizer settings to not read in occFactors.csv, as that file has been difficult to manage and it turns out is not needed at all.
The visualizer will no longer crash if occFactors.csv is not present in the model run's input directory.
> Removed occFactors.csv from visualizer

- docs/application/ev-rebates.md
Updates the EV rebate documentation to indicate that users need to edit rebate values in parametersByYears.csv.
This should only update the EV rebate page in the documentation.
> Updated EV rebate documentation to reflect that values are now edited in parametersByYears.csv

- docs/calib_valid/calib_overview.md
- docs/calib_valid/calibration.md
- docs/calib_valid/convergence.md
- docs/calib_valid/validation.md
- docs/design/demand/cvm.md
- mkdocs.yml
Create a new section in the top navigation bar for calibration and validation. Move the commercial vehicle demand page to "model design" section for now.
Calibration and validation is more important and merits a separate section in the navigation bar. It will be easier for users to find those details from the home page.
None.
> Docs site restructure to include a new section on calibration and validation

- docs/reports.md
Correct unit mistake in reports page: from seconds to minutes 
For columns ABTX_EA, ABTX_AM, ABTX_MD, ABTX_PM, ABTX_EV, BATX_EA, BATX_AM, BATX_MD, BATX_PM, BATX_EV in Loaded Highway Network File (hwytcad.csv)
> Correct Typo mistake in reports page (seconds to minutes)

- docs/running.md
Fixed broken image references where .jpg extensions needed to be capitalized to .JPG for newly uploaded images under [Pull Request #299](https://github.com/SANDAG/ABM/pull/299).
All images should now be correctly displayed within the wiki page.
None
> Update running.md to fix image referencing

- docs/design/supply/bike-logsums.md
Documentation mistakenly claimed that bike logsum process wrote outputs to the input folder. This has been fixed, with clarification on how files are copied from input folder when skipping this process.
Fixes mistake in documentation
> Fix output directory mistake in bike logsum documentation

- src/main/python/datalake_exporter.py
Release of v15.3.0 is imminent. Datalake folder on Azure has been updated. Other changes need to be made within Azure to start processing results to Unity Catalog (as opposed to Hive Metastore).
This will start writing model results to a new folder (abm_15_3_0) in Azure bronze container.
> Update write datalake folder on Azure for move to Unity Catalog

- src/main/emme/toolbox/import/import_network.py
#318
Updates import_network to read the toll factors file from the input directory instead of the network geodatabase. Also makes toll factors file required instead of optional and does not override HOV2 and HOV3 factors on HOV2 or HOV3 links if factors are defined in the file.
Updates to vehicle_class_toll_factors.csv will be properly read into the model network rather than using defaults
[AB#2073](https://dev.azure.com/SANDAG-ADS/3af839ac-e181-4605-b11c-60f38a706246/_workitems/edit/2073)
> Fix reading vehicle_class_toll_factors.csv

- src/main/resources/abm3_settings.yaml
Changed MGRA values for loc4, loc5, and rental in the SAN airport section of abm3_settings.yaml to reflect Series 15 MGRA values
The changes in this pull request update the SDIA access MGRA values for Rental Car Facility, Parking Location 4 and Parking Location 5 referenced in the SAN Airport Model. The values had been left unchanged when migrating from Series 14 to Series 15 and hence were spatially referencing locations that were not related to SAN Airport activities. 
The MGRAs were updated as follows:
| accessOptions           | Original Series 14  MGRA Value | Updated Series 15  MGRA Value |
|-----------|--------------------------------|-------------------------------|
| RENTAL    | 2994                           | 11244                         |
| PARK_LOC4 | 6528 …
> Update SDIA MGRAs to Series 15 

- input/model/vehicle_class_toll_factors.csv
- src/main/emme/toolbox/import/import_network.py
#322 
Updates network import to read HOV column in toll factors file, applying toll factors by facility name, HOV type, and time of day. Previously toll factors were only applied by facility name and time of day. Renames IHOV to HOV in toll factors file.
This allows multiple toll factors on the same facility if a facility contains multiple HOV types. 
> Use HOV type as a key for toll factor

- src/main/emme/toolbox/assignment/traffic_assignment.py
- src/main/emme/toolbox/import/import_network.py
This pull request updates the way Emme establishes link mode availability. It had previously been handled across both the import network and traffic assignment steps, however it is cleaner and clearer to entirely handle it within the import network step. 
The pull request additionally removes hard-coded project values related to I-15 managed lanes, which had initially been incorporated into the import network step to account for base (then 2016) scenario calibrations. 
The changes from the pull request result in expected link availability coding and also makes the code logic easier to follow given it no longer spans across more than one script. 
A few examples of link mode availability coding with the change in place and with access links coded as HOV 1:
1. This section shows the north …
> Issue 323: adjust link mode availability

- docs/inputs.md
The density fields that are added to the MGRA file at the start of the model run are not the density values for the MGRAs. Rather, they are the [density of an area within 0.65 miles of the MGRA](https://github.com/SANDAG/ABM/blob/main/src/main/emme/toolbox/import/run4Ds.py#L263-L287). This led to some confusion among SANDAG staff as there are MGRAs with no population that have a population density greater than zero. This pull request updates the documentation to clarify how the density fields are actually defined.
The definitions of the density fields in the documentation will be clearer.
> Clarification of density definitions in the documentation

- src/asim/configs/resident/tour_mode_choice.csv
- src/asim/configs/resident/trip_mode_choice.csv
This pull request replaces logical ands with multiplication operators in a couple lines in both the tour and trip mode choice specification files. The expressions should multiply the Boolean variable of not being an ebike owner by the rental time and cost, but by using the logical and they'll return a value of 1 regardless of what the time or cost is.
This fixes issue #207.
This will likely decrease the trips that choose e-bike as their mode. The extent of which is not yet known and further recalibration may need to be done.
> Replace logical and with multiplication in ebike utility calculation in mode choice spec files

- src/asim/configs/resident/tour_mode_choice_coefficients.csv
Adjusted shared ebike calibration given fix in #359. Target is shared ebike 0.25% of bike-adjacent tours, see #258. Also adjusted transit onboard coefficient due to increase in transit boardings in 15.3.1 (not fully tested)
Increase in shared ebike micromobility trips, decrease in transit trips
> Recalibrate shared ebike, adjust transit onboard

- docs/inputs.md
We identified errors in the data dictionary for the "microtransit" and "nev" columns. Their definitions have been corrected to represent the microtransit service area ID and the NEV service area ID, respectively.
> Documentation: correct fields definitions in land use file
