src/main/python/calculate_micromobility.py

This commit changes the behavior of the micromobility script that processes the `walkMgraEquivMinutes.csv` and `walkMgraTapEquivMinutes.csv` files.
Previous behavior was to overwrite the "actual" column with the calculated micromobility generalized time. Now the script writes two new files called `microMobilityMgraEquivMinutes.csv` and `microMobilityMgraTapEquivMinutes.csv` with the following columns:
- orig mgra ID
- dest mgra/tap ID
-  `walkTime`: the input column used for walk time. "actual" for the MGRA-MGRA file, "boardingActual" for the TAP file.
-  `mmTime`: the OD micromobility travel time + rental time + access time
- `mmCost`: variable cost * travel time + fixed cost
- `mmGenTime`: mmTime + mmCost converted to time + constant
- `minTime`: the minimum value of `walkTime` vs. …

Python: refactor micromobility script

---

src/main/resources/sandag_abm.properties

edited properties related to new Airport model; related to whether a scenario is a base run or not - credit @JiaXu1024

(ABM1430) sandag_abm.properties updates

---

.gitignore
src/asim/extensions/write_to_datalake.py

write_to_datalake should now detect the git branch and commit hash when the .git folder is in src/asim

Git branch and commit fix

---

src/asim/configs/resident/settings.yaml

Adds column from input households to output households for group quarters
https://dev.azure.com/SANDAG-ADS/ORTAD/_workitems/edit/349

Get group quarters from input households

---

src/asim/configs/airport.CBX/settings.yaml
src/asim/configs/airport.SAN/settings.yaml
src/asim/configs/crossborder/settings.yaml
src/asim/configs/resident/settings.yaml
src/asim/configs/visitor/settings.yaml
src/asim/configs/visitor/settings_visitor.yaml
src/asim/extensions/write_to_datalake.py

Fixes [AB#393](https://dev.azure.com/SANDAG-ADS/3af839ac-e181-4605-b11c-60f38a706246/_workitems/edit/393)

Add model name to settings.yaml

---

src/main/emme/toolbox/master_run.py
src/main/emme/toolbox/utilities/properties.py

changes to properties file - introduces checkbox to SANDAG EMME toolbox
changes to master_run file - option to skip triggering write_metadata() function
NOTE - a lot of whitespaces are removed in properties.py, lines of interest have comments to flag

abm3 - skip scenario guid creation in EMME GUI

---

src/asim/configs/common/outputs.yaml
src/asim/extensions/write_to_datalake.py

Fixes [AB#408](https://dev.azure.com/SANDAG-ADS/3af839ac-e181-4605-b11c-60f38a706246/_workitems/edit/408)

Remove columns from households that are in land use

---

src/asim/visualizer/visualizer/data/avgParkingDist.csv
src/asim/visualizer/visualizer/data/parkingDistanceProfile_vis.csv

The files included are needed or else PowerBI won't be able to open the visualizer

Add parking location summary placeholders

---

src/main/emme/toolbox/utilities/run_summary.py

Remove suffix from step name in generated runtime_summary.csv

Remove suffix in runtime summary

---

src/asim-cvm/configs/route_stop_purpose.csv
src/asim-cvm/configs/route_stop_purpose_coefficients.csv

Added calibration coefficients for terminate purpose for SUT and MUT and calibrated them

SUT/MUT Route Termination Calibration

---

docs/inputsandoutputs.md

This pull request updates the input output markdown file with latest updates according to comments from SANDAG

Abm3 develop wiki update

---

docs_requirements.txt
mkdocs.yml

Added plugin installation and referral.

Changes to install mermaid for github docs

---

docs/design.md
docs/inputs.md
docs/outputs.md
mkdocs.yml

Cleaned and added inputs.md & outputs.md
Added wrap command to keep the text inside the flowchart box

updating table of content and wraping flowchart

---

src/asim/visualizer/visualizer/hts_2022/autoOwnership_AV_ebike.csv

Added missing input file to **..\src\asim\visualizer\visualizer\hts_2022** as the visualizer script will fail if it's missing.
Will allow the visualizer to successfully run and avoid having to spend time fetching the file.
None

Add autoOwnership_AV_ebike.csv

---

src/main/python/datalake_exporter.py

migrate database
change database to variable in datalake_exporter.py in order to easily change it to a read-in property in upcoming changes
migrate database
- [X ] New feature (non-breaking change which adds functionality)
ran datalake exporter for existing scenario to write to dev
- [X ] My code follows the style guidelines of this project
- [X ] My changes generate no new warnings
testing process was pretty slow, datalake exporter may require investigation if this continues

Update datalake_exporter.py database

---

src/main/python/pythonGUI/createStudyAndScenario.py

Update GUI to use S0 version 19 and S1 version 20 land use
Use most up to date land use
S2 and S3 land use are not updated

Update S0 and S1 land use paths to versions 19 and 20

---

src/asim/configs/resident/workplace_location_coefficients.csv

The value `coef_dist` in workplace_location_coefficients.csv was increased by 5%.
A test of the resident model with a 25% sample found that the average distance to work increased from 10.64 miles to 11.21 miles. It is hoped that this will get modeled freeway volumes closer to observed counts.

Increase average distance to work

---

docs/applying.md

Adds documentation on the EV rebates.
Only updated documentation files.

Add documentation on applying EV rebates

---

src/asim/configs/resident/vehicle_type_choice_op4_coefficients.csv

The number of chargers for each scenario year is increasing. As the EV ownership is very sensitive to that, the calibration constants needed to be recalibrated.
The coefficients were decreased to counter the increase in the number of chargers and keep the EV ownership rates at the values set by planners.

EV Recalibration (2022, 2035)

---

src/asim/configs/resident/vehicle_type_choice_op4_coefficients.csv

Due to the increase in the number of chargers per capita, the EV coefficients for 2050 needed to be recalibrated to match the targets given to us by planners.
The EV ownership should be reduced compared to previous values.

Recalibrated 2050 EV Coefficients

---

docs/release-notes.md

The release notes for release 15.1.0 are added to the documentation.

Release 15_1_0 release notes

---

src/asim/configs/resident/tour_mode_choice_coefficients.csv

Calibrated tour mode choice model to decrease transit ridership
expected ridership is approximately 280K with this update. 
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

updated tour mode chocie coef

---

src/main/emme/toolbox/master_run.py
src/main/python/datalake_exporter.py

Write the source paths of the network and land use (currently stored in abm properties) to the scenario table on the datalake
Provide easy reference to network and land use versions used for a given model run
Silver scenario table needs to be updated in prod

Write network and land use paths to the scenario table

---

src/main/python/datalake_exporter.py

remove file no longer needed
cleanup
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

Update datalake_exporter.py, remove microMgraEquivMinutes.csv

---

src/asim/configs/airport.CBX/trip_mode_choice.yaml
src/asim/configs/airport.CBX/write_trip_matrices.yaml
src/asim/configs/airport.SAN/trip_mode_choice.yaml
src/asim/configs/airport.SAN/write_trip_matrices.yaml
src/asim/configs/common_airport/constants.yaml
src/asim/configs/common_airport/initialize_tours.yaml
src/asim/configs/crossborder/trip_mode_choice.yaml
src/asim/configs/crossborder/write_trip_matrices.yaml
src/asim/configs/resident/write_trip_matrices.yaml
src/asim/configs/visitor/trip_mode_choice.yaml
src/asim/configs/visitor/write_trip_matrices.yaml

Removes some constants from trip_mode_choice.yaml and write_trip_matrices.yaml that are already defined in common/constants.yaml. This primarily includes vot_threshold constants. Also removes some unused constants in crossborder and visitor.
Closes #211 
Improves cleanliness of config files and reduces number of locations where config values need to be updated

Some config cleanup

---

src/main/python/AMTravelTimeReporterConfigs.yaml
src/main/python/MDTravelTimeReporterConfigs.yaml
src/main/python/TravelTimeReporter.py

This removes the initial wait time from the transit times to match the definition of the metric given.
More MGRAs should be accessible to other MGRAs within a certain time by transit.
This change has not yet been tested.

Removed initial wait time from transit travel time calculations

---

src/main/emme/toolbox/master_run.py
src/main/resources/runValidation.bat

This change will remove the earlier version of the ABM2+ validation process and replace with the ABM3 version which is compatible with TNED. The validation process will launch automatically only if the scenario year is a base 2022 scenario. 
This change will eliminate the need to manually run the validation procedure after an ABM3 run completes. The validation procedure has been incorporated into the master run process and will automatically launch at the end of a 2022 base year scenario.
For now, the newly added runValidation.bat file points to the T:\ABM\\***release_test***\\tools\PowerBI_validation_tool location rather than the …

Update Validation for ABM3

---

docs/design/supply/network-import-tned.md

This is the first draft of the import network ABM3 wiki page. It provides a description of the required network files along with a general workflow of the main steps the Emme import network procedure carries out.
This will allow users to know which files are required to run the ABM3 import network procedure and will lay out a general workflow of the main steps of the process. It also provides a link to the main Python script along with an older EMME SANDAG report that provides greater details of the import network step (among others). 
None.

Import Network ABM3 Wiki Page

---

docs/design/supply/transit-skims-assign.md

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
Improved documentation
None

Documentation: Transit Skimming and Assignment

---

src/main/emme/toolbox/master_run.py
src/main/emme/toolbox/utilities/properties.py

Adds checkbox option in master run toolbox to skip validation step
Allows the step to be skipped to prevent errors for test scenarios where required files don't exist

Add option to skip validation

---

src/asim/scripts/resident/2zoneSkim.py

After previous PR https://github.com/SANDAG/ABM/pull/242, premium transit MAZ-Stop pairs that should be inaccessible by walk became accessible and used straight-line distance. This was caused by the missing_maz calculation. This update removes missing_maz for MAZ-STOP, as do not need to add missing MAZs for transit access. 
Less MGRAs are within walk distance of premium stops

Fix inaccessible premium MAZ-stop pairs

---

src/asim/configs/airport.CBX/trip_mode_choice.yaml
src/asim/configs/airport.SAN/trip_mode_choice.yaml

Closes #127 and #128; Removed redundant settings from airport models that wasn't needed.
Would improve clarity of model configs.
- Looked over the coefficients.csv for both airports to see if removed settings were used.

Remove unused settings kng

---

docs/design/report/report.md

[AB#1251](https://dev.azure.com/SANDAG-ADS/3af839ac-e181-4605-b11c-60f38a706246/_workitems/edit/1251)  Document Reporting Process
improve documentation
None

update reporting docs

---

docs/release-notes.md

Adds the v15.2.0 release notes to the model documentation.
There will be no impact on the model results, only the documentation site.
N/A

V15 2 0 release notes

---

docs/design/design.md

Editing the overall design page with text updates, new flow-chart.
This should make the overall design page easier to understand and more beginner friendly for those who are unfamiliar with the concepts of transportation modeling.
- Developed locally and checked on web browser for complete functionality.
There still needs to be potential improvements in the flowchart/text and overall feedback would be appreciated in making this page more useful and user/beginner-friendly.

Documentation: updating overall design page

---

docs/outputs.md

On QA'ing  'output' page on documentation website, the following checks were conducted:
1. list of output files
2. data descriptions
The inconsistent files and data descriptions are being resolved.
Attempt to resolve some inconsistencies to get updated wiki.
- [X ] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings

Documentation: editing of outpage page of wiki for consistency

---

src/asim/configs/resident/telecommute_frequency_coeffs.csv
src/asim/configs/resident/work_from_home_coeffs.csv

RSG had adjusted the out-of-direction distance in stop location, resulting in a decrease in VMT. This pull request reduces working from home and telecommuting to increase VMT back to the target.
The VMT is expected to increase by 200-300k.

Decrease work from home/telecommuting

---

docs/outputs.md

Adding Output files and all file descriptions for HTM and Output files and 6 file descriptions for CVM models to documentation wiki
Inserted the required missing documentation 
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

 Adding CVM and HTM outputs to documentation wiki

---

docs/release-notes.md

Adds the release notes for version 15.2.1.
The release notes for version 15.2.1 will be in the documentation.

Added v15.2.1 release notes

---

src/main/python/TravelTimeReporter.py

This adds the updates made in ABM release 15.2.1 into the ActivitySim 1.3.2 upgrade branch.
The final merge into ABM3_develop should be easier.
N/A

Incorporate ABM v15.2.1 into ActivitySim 1.3.2 upgrade

---

src/asim/configs/common/outputs.yaml
src/asim/configs/crossborder/write_trip_matrices_annotate_trips_preprocessor.csv
src/asim/configs/resident/write_trip_matrices_annotate_trips_preprocessor.csv
src/asim/configs/visitor/write_trip_matrices_annotate_trips_preprocessor.csv

Revert "Add flexible fleet boarding attributes"

---

src/asim/configs/common/outputs.yaml

Removes time, dist, cost skim columns from trips table
Slightly reduce trips file size

Remove unnecessary skim columns from trip table

---

src/main/resources/runSandagAbm_Preprocessing.cmd

Removing parking folder from current ABM3 output
Updating output because the parking files are preprocessed by land use prep tool, there are no parking outputs from activity sim.

Parking update

---

docs/outputs.md

Cleaning up documentation and correction of typos.
Documentation updates.

Model Wiki updates

---

docs/calib_valid/calib_overview.md

Populated the calibration overview section and added pdf report from March 2024.
This page could have a chronological record of all calibration and validation efforts going forward.
None.

Updated docs for calibration overview section and added pdf report

---

docs/outputs.md

Add units to the descriptions of traffic skims and transit skims.
Add descriptions of trip tables to the output page.

Added units to skims description; added description to trip tables

---

docs/inputs.md

Add NAICS code descriptions to the wiki input page.
-  Add the definition to 'naics2_original_code' under Population Synthesizer Person Data
-  Add the NAICS code to 'MGRA_BASED_INPUT_SCENARIO_YEAR.CSV' for columns: 
1. emp_ag_min: 
2. emp_bus_svcs
3. emp_fin_res_mgm
4. emp_educ
5. emp_hlth
6. emp_ret
7. emp_trn_wrh_con
8. emp_utl_mnf_whl
9. emp_ent
10. emp_accm
11. emp_food
12. emp_oth
documentation update

Add NAICS code reference in Input page

---

docs/release-notes.md

Adds release notes for version 15.2.2
The wiki page will be updated with new release notes

Add v15.2.2 release notes

---

src/main/python/datalake_exporter.py

To include validation files in the list of files that are uploaded to datalake.
There should be no impact on any model results. 
Validation tool need to be updated in release folder.

update datalake exporter to include validation files

---

src/main/python/validation.py

In the previous validation update, the file FHWA_Guidelines.xlsx was removed from the observed_data folder. However, the validation.py script still attempts to read this now-missing file. This commit removes the code related to reading the FHWA file and its associated functions.
No impact to the outputs that are used in the validation dash tool.
Updated the validation.py script in a completed scenario ("T:\STORAGE-63T\sxu_tests\2022_v1530_validation") and run the validation step. The validation outputs were generated without any errros.

remove FHWA guideline from validation script

---

src/asim/scripts/environment.yml
src/asim/scripts/requirements.txt

Pull Request #320 created an environment that was incorrect, as not all libraries were included or installed properly. This request does the following:
- Move `git` (and `gitpython`) from requirements.txt back to environment.yml
- Add `seaborn` and `openpyxl` to requirements.txt
Any environment created using these files should be able to run ABM3 from start to finish with no issues

Fix asim_140 environment creation files

---

docs/release-notes.md

This pull request adds the release notes for v15.3.1.
The documentation will be updated to include the new release notes.

Add v15.3.1 release notes
